// react-poc/leasingborsen-react-production/src/pages/About.tsx
import React from 'react'
import BaseLayout from '@/components/BaseLayout'

const About: React.FC = () => {
  return (
    <BaseLayout>
      <div className="min-h-[50vh] flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-foreground mb-4">Om Os</h1>
          <p className="text-muted-foreground">About page coming soon...</p>
        </div>
      </div>
    </BaseLayout>
  )
}

export default About

// src/pages/About.vue
        <template>
          <BaseLayout>
            <h1 class="text-3xl font-bold text-base-content mb-6">About</h1>
            <p class="text-base-content">This page is ready for content.</p>
          </BaseLayout>
        </template>

        <script setup>
        import BaseLayout from '../components/BaseLayout.vue'
        </script>
