// react-poc/leasingborsen-react-production/src/components/BaseLayout.tsx
import React from 'react'
import ModernHeader from '@/components/ModernHeader'
import Footer from '@/components/Footer'

interface BaseLayoutProps {
  children: React.ReactNode
  /** Whether to show the footer (default: true) */
  showFooter?: boolean
  /** Whether to show the header (default: true) */
  showHeader?: boolean
  /** Additional CSS classes for the main content area */
  className?: string
}

const BaseLayout: React.FC<BaseLayoutProps> = ({
  children,
  showFooter = true,
  showHeader = true,
  className = ''
}) => {
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      {/* Header */}
      {showHeader && <ModernHeader />}
      
      {/* Main Content */}
      <main className={`flex-1 w-full ${className}`}>
        {children}
      </main>
      
      {/* Footer */}
      {showFooter && <Footer />}
    </div>
  )
}

export default BaseLayout

// src/components/BaseLayout.vue
<script setup>
import Header from './Header.vue'
</script>

<template>
  <div class="min-h-screen flex flex-col bg-base-200">
    <!-- Header -->
    <Header />

    <!-- Main content -->
    <main class="flex-1 w-full py-6">
      <div class="mx-auto w-full max-w-[1440px] px-4 md:px-16">
        <slot />
      </div>
    </main>

    <!-- Footer -->
    <footer class="footer footer-center p-4 bg-base-300 text-base-content">
      <div class="mx-auto w-full max-w-[1440px] px-4 md:px-16">
        <p>© 2025 Leasingbørsen</p>
      </div>
    </footer>
  </div>
</template>
