// react-poc/leasingborsen-react-production/src/components/ListingCard.tsx
import React, { useState, useMemo, useCallback } from 'react'
import { Link } from 'react-router-dom'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Skeleton } from '@/components/ui/skeleton'
import { 
  Fuel, 
  Settings, 
  Car, 
  Gauge, 
  AlertCircle, 
  RotateCcw, 
  Flag,
  Loader2
} from 'lucide-react'
import { useImageLazyLoading } from '@/hooks/useImageLazyLoading'
import type { CarListing } from '@/types'

interface ListingCardProps {
  car?: CarListing | null
  loading?: boolean
}

const ListingCardComponent: React.FC<ListingCardProps> = ({ car, loading = false }) => {
  
  // Optimized image loading with shared intersection observer
  const {
    imageRef,
    imageLoaded,
    imageError,
    retryImage,
    canRetry
  } = useImageLazyLoading(car?.processed_image_grid || car?.image, {
    threshold: 0.1,
    rootMargin: '200px',
    maxRetries: 3
  })
  
  // Interaction states
  const [showRipple, setShowRipple] = useState(false)
  const [navigating, setNavigating] = useState(false)
  const [isPressed, setIsPressed] = useState(false)
  
  // Memoized skeleton content for consistent rendering
  const skeletonWidths = useMemo(() => ['w-24', 'w-32', 'w-28', 'w-36', 'w-20', 'w-16'], [])
  const getRandomWidth = useCallback(() => 
    skeletonWidths[Math.floor(Math.random() * skeletonWidths.length)], 
    [skeletonWidths]
  )
  
  // Error recovery actions
  const handleRetryImage = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    retryImage()
  }, [retryImage])
  
  const reportIssue = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    console.error('Issue reported for car:', car?.id || car?.listing_id)
  }, [car?.id, car?.listing_id])
  
  // Optimized interaction handlers with useCallback
  const onCardClick = useCallback(() => {
    // Immediate visual feedback
    setShowRipple(true)
    setIsPressed(true)
    
    // Clear ripple after animation
    const rippleTimer = setTimeout(() => {
      setShowRipple(false)
      setIsPressed(false)
    }, 400)
    
    // Show loading if navigation is slow
    const navigationTimer = setTimeout(() => {
      setNavigating(true)
    }, 150)
    
    // Cleanup function
    return () => {
      clearTimeout(rippleTimer)
      clearTimeout(navigationTimer)
      setNavigating(false)
    }
  }, [])
  
  // Memoized utility functions for better performance
  const formatPrice = useCallback((price?: number) => {
    return price ? `${price.toLocaleString('da-DK')} kr/måned` : 'Pris ikke tilgængelig'
  }, [])
  
  const formatMileage = useCallback((mileage?: number) => {
    return mileage ? `${mileage.toLocaleString('da-DK')} km/år` : 'Km ikke angivet'
  }, [])
  
  // Memoized computed values
  const displayPrice = useMemo(() => formatPrice(car?.monthly_price), [car?.monthly_price, formatPrice])
  const displayMileage = useMemo(() => formatMileage(car?.mileage_per_year), [car?.mileage_per_year, formatMileage])
  const carAltText = useMemo(() => 
    `${car?.make} ${car?.model} ${car?.variant} - ${car?.fuel_type} - ${displayPrice}`,
    [car?.make, car?.model, car?.variant, car?.fuel_type, displayPrice]
  )
  
  // Enhanced Skeleton State with Realistic Content Structure
  if (loading) {
    return (
      <Card className="bg-card shadow-lg border border-border/50 rounded-xl overflow-hidden">
        {/* Image skeleton with enhanced shimmer */}
        <div className="relative overflow-hidden">
          <Skeleton className="w-full h-56" />
        </div>
        
        <CardContent className="p-4 pt-2">
          {/* Smart title & variant skeleton */}
          <div className="space-y-3 mb-4">
            {/* Car make and model (realistic lengths) */}
            <div className="flex items-center space-x-2">
              <Skeleton className="h-7 w-20" />
              <Skeleton className="h-7 w-28" />
            </div>
            {/* Variant */}
            <Skeleton className="h-4 w-36" />
          </div>

          {/* Smart price skeleton */}
          <div className="space-y-2 mb-4">
            {/* Price components */}
            <div className="flex items-baseline space-x-1">
              <Skeleton className="h-6 w-20" />
              <Skeleton className="h-5 w-12" />
            </div>
            {/* Secondary info */}
            <Skeleton className="h-3 w-full" />
          </div>

          {/* Divider */}
          <Separator className="my-4" />

          {/* Smart specs skeleton */}
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              {Array.from({ length: 4 }).map((_, index) => (
                <div key={`skeleton-spec-${car?.listing_id || 'loading'}-${index}`} className="flex items-center gap-2">
                  <Skeleton className="w-4 h-4 rounded-full" />
                  <Skeleton className={`h-3 ${getRandomWidth()}`} />
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  // Enhanced Real Content State
  if (!car || (!car.id && !car.listing_id)) {
    return null
  }

  return (
    <Link
      to={`/listing/${car.id || car.listing_id}`}
      className="block group no-underline relative"
      onClick={onCardClick}
    >
      {/* Click ripple effect */}
      {showRipple && (
        <div 
          className="absolute inset-0 bg-primary/10 rounded-lg animate-ping z-20"
          style={{animationDuration: '0.4s', animationIterationCount: 1}}
        />
      )}
      
      {/* Loading overlay for slow navigation */}
      {navigating && (
        <div className="absolute inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center rounded-lg z-30">
          <Loader2 className="w-6 h-6 animate-spin text-primary" />
        </div>
      )}

      {/* Enhanced card with improved shadcn/ui styling */}
      <Card 
        className={`bg-card shadow-lg border border-border/50 hover:shadow-xl hover:border-primary/30 hover:-translate-y-1 transition-all duration-300 rounded-xl overflow-hidden ${
          isPressed ? 'scale-95 shadow-md translate-y-0' : ''
        }`}
      >
        {/* Progressive Image Loading with Enhanced Error States */}
        <div className="relative overflow-hidden bg-gradient-to-br from-blue-50/80 to-blue-100/60 dark:from-blue-950/20 dark:to-blue-900/30">
          {/* Enhanced placeholder for missing images */}
          {!car.image && !car.processed_image_grid ? (
            <div className="bg-gradient-to-br from-muted to-muted/70 aspect-[4/3] flex items-center justify-center text-muted-foreground w-full h-56">
              <div className="text-center space-y-2">
                <div className="w-12 h-12 mx-auto bg-muted-foreground/10 rounded-full flex items-center justify-center">
                  <Car className="w-6 h-6 opacity-50" />
                </div>
                <span className="text-sm font-medium">Billede mangler</span>
              </div>
            </div>
          ) : !imageError ? (
            <>
              {/* Blurred thumbnail placeholder */}
              {car.thumbnail_base64 && !imageLoaded && (
                <div className="absolute inset-0 z-10">
                  <img 
                    src={car.thumbnail_base64} 
                    className={`w-full h-56 object-contain p-4 blur-sm scale-105 transition-opacity duration-300 ${
                      imageLoaded ? 'opacity-0' : ''
                    }`}
                    alt={`${car.make} ${car.model} thumbnail`}
                  />
                </div>
              )}
              
              {/* Gradient placeholder if no thumbnail */}
              {!car.thumbnail_base64 && !imageLoaded && (
                <div className="absolute inset-0 bg-gradient-to-br from-muted to-muted/70 animate-pulse z-10" />
              )}
              
              {/* High-resolution image - prefer processed grid image */}
              <img
                ref={imageRef}
                src={car.processed_image_grid || car.image}
                alt={carAltText}
                className={`w-full h-56 object-contain p-6 transition-opacity duration-500 ease-out ${
                  imageLoaded ? 'opacity-100' : 'opacity-0'
                }`}
                loading="lazy"
              />
            </>
          ) : (
            /* Enhanced error state with recovery actions */
            <div className="bg-gradient-to-br from-muted to-muted/70 h-56 flex flex-col items-center justify-center p-6">
              <div className="w-12 h-12 bg-destructive/10 rounded-full flex items-center justify-center mb-3">
                <AlertCircle className="w-6 h-6 text-destructive" />
              </div>
              <p className="text-sm text-center mb-4 text-muted-foreground font-medium">
                Billedet kunne ikke indlæses
              </p>
              <div className="flex gap-2">
                <Button 
                  onClick={handleRetryImage} 
                  size="sm"
                  variant="outline"
                  disabled={!canRetry}
                  className="text-xs"
                >
                  <RotateCcw className="w-3 h-3 mr-1" />
                  {!canRetry ? 'Max forsøg' : 'Prøv igen'}
                </Button>
                <Button 
                  onClick={reportIssue} 
                  size="sm"
                  variant="ghost"
                  className="text-xs"
                >
                  <Flag className="w-3 h-3 mr-1" />
                  Rapportér
                </Button>
              </div>
            </div>
          )}
          
          {/* Enhanced overlay gradient on hover */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/0 via-transparent to-transparent group-hover:from-black/10 transition-all duration-300"></div>
        </div>

        {/* Enhanced Card Body Content */}
        <CardContent className="p-5">
          {/* Enhanced Title & Variant */}
          <div className="space-y-0 mb-4">
            <h3 className="text-xl font-bold text-foreground leading-tight group-hover:text-primary transition-colors duration-200">
              {car.make} {car.model}
            </h3>
            {car.variant && (
              <p className="text-base text-muted-foreground font-normal leading-relaxed">{car.variant}</p>
            )}
          </div>

          {/* Enhanced Specs Grid */}
          <div className="mb-4">
            <div className="grid grid-cols-2 gap-x-4 gap-y-3">
              <div className="flex items-center gap-2.5 text-sm text-muted-foreground/80 group-hover:text-foreground transition-colors duration-200">
                <div className="w-4 h-4 flex items-center justify-center flex-shrink-0">
                  <Fuel className="w-4 h-4" />
                </div>
                <span className="font-normal truncate">{car.fuel_type || '–'}</span>
              </div>
              <div className="flex items-center gap-2.5 text-sm text-muted-foreground/80 group-hover:text-foreground transition-colors duration-200">
                <div className="w-4 h-4 flex items-center justify-center flex-shrink-0">
                  <Settings className="w-4 h-4" />
                </div>
                <span className="font-normal truncate">{car.transmission || '–'}</span>
              </div>
              <div className="flex items-center gap-2.5 text-sm text-muted-foreground/80 group-hover:text-foreground transition-colors duration-200">
                <div className="w-4 h-4 flex items-center justify-center flex-shrink-0">
                  <Car className="w-4 h-4" />
                </div>
                <span className="font-normal truncate">{car.body_type || '–'}</span>
              </div>
              <div className="flex items-center gap-2.5 text-sm text-muted-foreground/80 group-hover:text-foreground transition-colors duration-200">
                <div className="w-4 h-4 flex items-center justify-center flex-shrink-0">
                  <Gauge className="w-4 h-4" />
                </div>
                <span className="font-normal truncate">{car.horsepower ? `${car.horsepower} hk` : '–'}</span>
              </div>
            </div>
          </div>

          {/* Divider */}
          <Separator className="my-5" />

          {/* Enhanced Price Display */}
          <div className="space-y-2">
            <p className="text-2xl font-bold text-primary group-hover:text-primary/90 transition-colors duration-200 leading-none">
              {displayPrice}
            </p>
            <div className="flex items-center gap-3 text-xs text-muted-foreground leading-relaxed">
              <span className="font-medium">{displayMileage}</span>
              {car.first_payment && (
                <>
                  <span className="text-muted-foreground/50">•</span>
                  <span className="font-medium">Udbetaling: {car.first_payment.toLocaleString('da-DK')} kr</span>
                </>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </Link>
  )
}

// Memoized component for better performance
const ListingCard = React.memo(ListingCardComponent)

export default ListingCard

// src/components/ListingCard.vue
<script setup>
import { ref, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import { Fuel, Settings, Car, Gauge } from 'lucide-vue-next'

const props = defineProps({
  car: {
    type: Object,
    required: false,
    default: null
  },
  loading: {
    type: Boolean,
    default: false
  }
})

const imageLoaded = ref(false)
const imageRef = ref(null)

onMounted(() => {
  // Only set up lazy loading if not in loading state and car exists
  if (!props.loading && props.car && imageRef.value) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const img = entry.target
          img.src = img.dataset.src
          img.onload = () => {
            imageLoaded.value = true
          }
          observer.unobserve(img)
        }
      })
    }, { threshold: 0.1 })
    
    observer.observe(imageRef.value)
  }
})
</script>

<template>
  <!-- Skeleton State -->
  <div 
    v-if="loading" 
    class="block rounded-lg hover:shadow-xl transition-all duration-300 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary/20 group no-underline mb-6"
  >
    <div class="card rounded-lg overflow-hidden">
      <!-- Image skeleton with shimmer -->
      <figure class="relative rounded-t-lg overflow-hidden bg-gray-100">
        <div class="w-full h-52 bg-gray-200 relative overflow-hidden">
          <!-- Shimmer effect -->
          <div class="absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent animate-shimmer"></div>
        </div>
      </figure>
      
      <!-- Title & Variant skeleton -->
      <div class="px-5 pt-4" style="height: 64.75px;">
        <div class="h-6 bg-gray-200 rounded w-3/4 leading-snug mb-1 animate-pulse"></div>
        <div class="h-4 bg-gray-200 rounded w-1/2 animate-pulse" style="animation-delay: 0.1s;"></div>
      </div>

      <!-- Price skeleton -->
      <div class="px-5 pt-3" style="height: 58px;">
        <div class="h-6 bg-gray-200 rounded w-2/3 mb-1 animate-pulse" style="animation-delay: 0.2s;"></div>
        <div class="h-3 bg-gray-200 rounded w-full animate-pulse" style="animation-delay: 0.3s;"></div>
      </div>

      <!-- Divider -->
      <div class="border-t border-dashed border-base-300 mx-5 my-3"></div>

      <!-- Specs skeleton -->
      <div class="px-5 pb-5" style="height: 68px;">
        <div class="grid grid-cols-2 gap-y-2 text-sm">
          <div class="flex items-center gap-2">
            <div class="w-4 h-4 bg-gray-200 rounded animate-pulse" style="animation-delay: 0.4s;"></div>
            <div class="h-3 bg-gray-200 rounded w-12 animate-pulse" style="animation-delay: 0.5s;"></div>
          </div>
          <div class="flex items-center gap-2">
            <div class="w-4 h-4 bg-gray-200 rounded animate-pulse" style="animation-delay: 0.6s;"></div>
            <div class="h-3 bg-gray-200 rounded w-16 animate-pulse" style="animation-delay: 0.7s;"></div>
          </div>
          <div class="flex items-center gap-2">
            <div class="w-4 h-4 bg-gray-200 rounded animate-pulse" style="animation-delay: 0.8s;"></div>
            <div class="h-3 bg-gray-200 rounded w-10 animate-pulse" style="animation-delay: 0.9s;"></div>
          </div>
          <div class="flex items-center gap-2">
            <div class="w-4 h-4 bg-gray-200 rounded animate-pulse" style="animation-delay: 1.0s;"></div>
            <div class="h-3 bg-gray-200 rounded w-14 animate-pulse" style="animation-delay: 1.1s;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Real Content State -->
  <RouterLink
    v-else-if="car && (car.id || car.listing_id)"
    :to="{ name: 'Listing', params: { id: car.id || car.listing_id } }"
    class="block rounded-lg hover:shadow-xl transition-all duration-300 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary/20 group no-underline mb-6"
  >
    <div class="card rounded-lg overflow-hidden">
      <!-- Image with lazy loading and placeholder for missing images -->
      <figure class="relative rounded-t-lg overflow-hidden bg-gray-100">
        <!-- Image placeholder for missing images -->
        <div 
          v-if="!car.image"
          class="bg-base-200 aspect-video flex items-center justify-center text-gray-400 w-full h-52"
        >
          <div class="text-center">
            <Car class="w-8 h-8 mx-auto mb-2 opacity-50" />
            <span class="text-sm">Billede mangler</span>
          </div>
        </div>
        
        <!-- Actual image with lazy loading -->
        <template v-else>
          <!-- Blur placeholder -->
          <div 
            v-if="!imageLoaded"
            class="absolute inset-0 bg-gradient-to-br from-gray-200 to-gray-300 animate-pulse"
          />
          
          <img
            ref="imageRef"
            :data-src="car.image"
            :alt="`${car.make} ${car.model}`"
            class="w-full h-52 object-cover transition-opacity duration-500 ease-out"
            :class="{ 
              'opacity-0': !imageLoaded,
              'opacity-100': imageLoaded 
            }"
            loading="lazy"
          />
        </template>
        
        <!-- Overlay gradient on hover -->
        <div class="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-all duration-300"></div>
      </figure>

      <!-- Title & Variant -->
      <div class="px-5 pt-4 pb-2">
        <h3 class="text-lg font-bold text-primary leading-snug group-hover:text-primary/90 transition-colors duration-200">
          {{ car.make }} {{ car.model }}
        </h3>
        <p class="text-sm text-base-content/60 mt-1">{{ car.variant }}</p>
      </div>

      <!-- Price -->
      <div class="px-5 py-2">
        <p class="text-lg font-semibold text-primary group-hover:text-primary/90 transition-colors duration-200">
          {{ car.monthly_price ? `${car.monthly_price.toLocaleString('da-DK')} kr. / måned` : 'Pris ikke tilgængelig' }}
        </p>
        <p class="text-xs text-base-content/50 mt-0.5">
          {{ car.mileage_per_year ? `${car.mileage_per_year.toLocaleString()} km/år` : 'Km ikke angivet' }}
          •
          {{ car.first_payment ? `Udbetaling: ${car.first_payment.toLocaleString()} kr` : 'Udbetaling ikke angivet' }}
        </p>
      </div>

      <!-- Divider -->
      <div class="border-t border-dashed border-base-300 mx-5 my-3 group-hover:border-base-400 transition-colors duration-200"></div>

      <!-- Specs -->
      <div class="px-5 pb-5 pt-2">
        <div class="grid grid-cols-2 gap-y-2 text-sm text-base-content/60">
          <div class="flex items-center gap-2 group-hover:text-base-content/80 transition-colors duration-200">
            <Fuel class="w-4 h-4 text-base-content/50 group-hover:text-base-content/70 transition-colors duration-200" /> 
            {{ car.fuel_type || '–' }}
          </div>
          <div class="flex items-center gap-2 group-hover:text-base-content/80 transition-colors duration-200">
            <Settings class="w-4 h-4 text-base-content/50 group-hover:text-base-content/70 transition-colors duration-200" /> 
            {{ car.transmission || '–' }}
          </div>
          <div class="flex items-center gap-2 group-hover:text-base-content/80 transition-colors duration-200">
            <Car class="w-4 h-4 text-base-content/50 group-hover:text-base-content/70 transition-colors duration-200" /> 
            {{ car.body_type || '–' }}
          </div>
          <div class="flex items-center gap-2 group-hover:text-base-content/80 transition-colors duration-200">
            <Gauge class="w-4 h-4 text-base-content/50 group-hover:text-base-content/70 transition-colors duration-200" /> 
            {{ car.horsepower ? `${car.horsepower} hk` : '–' }}
          </div>
        </div>
      </div>
    </div>
  </RouterLink>
</template>

<style scoped>
/* Custom shimmer animation */
@keyframes shimmer {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(100%);
  }
}

.animate-shimmer {
  animation: shimmer 2s infinite;
}

/* Remove text underlines from RouterLink and all child elements */
a {
  text-decoration: none !important;
}

a * {
  text-decoration: none !important;
}

a:hover,
a:hover *,
a:focus,
a:focus * {
  text-decoration: none !important;
}
</style>
