// react-poc/leasingborsen-react-production/src/components/PopularCategories.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Card, CardContent } from '@/components/ui/card'
import { Zap, DollarSign, Users, Building, Settings } from 'lucide-react'

// More specific TypeScript types
interface CategoryFilters {
  fuel_type?: 'Electric' | 'Petrol' | 'Diesel' | 'Hybrid'
  price_max?: number
  body_type?: 'SUV' | 'Microcar' | 'Sedan' | 'Hatchback' | 'Stationcar'
  transmission?: 'Automatic' | 'Manual'
}

interface CategoryItem {
  id: string
  label: string
  subtitle: string
  icon: React.ComponentType<{ className?: string }>
  filters: CategoryFilters
}

interface PopularCategoriesProps {
  title?: string
  categories?: CategoryItem[]
  className?: string
  onNavigationError?: (error: Error) => void
}

// Separate CategoryCard component for better composition
interface CategoryCardProps {
  category: CategoryItem
  onClick: (filters: CategoryFilters) => void
  isLoading?: boolean
}

const CategoryCard: React.FC<CategoryCardProps> = ({ 
  category, 
  onClick, 
  isLoading = false 
}) => {
  const IconComponent = category.icon

  const handleClick = () => {
    if (!isLoading) {
      onClick(category.filters)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if ((e.key === 'Enter' || e.key === ' ') && !isLoading) {
      e.preventDefault()
      onClick(category.filters)
    }
  }

  return (
    <Card
      role="button"
      tabIndex={0}
      aria-label={`Filter by ${category.label}: ${category.subtitle}`}
      className={`
        group cursor-pointer transition-all duration-300 
        hover:shadow-xl hover:-translate-y-1 
        border border-border/50 hover:border-primary/20 hover:bg-card/50
        focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2
        ${isLoading ? 'opacity-50 cursor-not-allowed' : ''}
      `}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      <CardContent className="p-4 lg:p-6">
        <div className="space-y-3 text-center">
          {/* Icon with primary color and hover animation */}
          <div className="flex justify-center">
            <div className="text-primary group-hover:text-primary group-hover:scale-110 transition-all duration-300">
              <IconComponent className="w-8 h-8 lg:w-10 lg:h-10" />
            </div>
          </div>
          
          {/* Title */}
          <h3 className="text-sm sm:text-base font-semibold text-foreground group-hover:text-primary transition-colors duration-200">
            {category.label}
          </h3>
          
          {/* Subtitle */}
          <p className="text-xs text-muted-foreground leading-relaxed">
            {category.subtitle}
          </p>
        </div>
      </CardContent>
    </Card>
  )
}

const defaultCategories: CategoryItem[] = [
  {
    id: 'electric',
    label: 'Elbiler',
    subtitle: 'Miljøvenlige valg',
    icon: Zap,
    filters: {
      fuel_type: 'Electric'
    }
  },
  {
    id: 'cheap',
    label: 'Billige biler',
    subtitle: 'Under 2.000 kr./md',
    icon: DollarSign,
    filters: {
      price_max: 2000
    }
  },
  {
    id: 'family',
    label: 'Familiebiler',
    subtitle: 'SUV & Stationcars',
    icon: Users,
    filters: {
      body_type: 'SUV'
    }
  },
  {
    id: 'city',
    label: 'Bybiler',
    subtitle: 'Kompakte & smarte',
    icon: Building,
    filters: {
      body_type: 'Microcar'
    }
  },
  {
    id: 'automatic',
    label: 'Automatgear',
    subtitle: 'Nem kørsel',
    icon: Settings,
    filters: {
      transmission: 'Automatic'
    }
  }
]

const PopularCategories: React.FC<PopularCategoriesProps> = ({
  title = "Populære kategorier",
  categories = defaultCategories,
  className = "",
  onNavigationError
}) => {
  const navigate = useNavigate()
  const [isNavigating, setIsNavigating] = useState(false)

  // Enhanced navigation function with error handling
  const navigateToCategory = async (filters: CategoryFilters) => {
    try {
      setIsNavigating(true)
      
      // Handle special case for family cars (multiple body types)
      if (filters.body_type === 'SUV') {
        navigate('/listings?body_type=SUV')
        return
      }
      
      // Convert filters to query parameters with proper validation
      const queryParams = new URLSearchParams()
      Object.entries(filters).forEach(([key, value]) => {
        if (value !== null && value !== undefined && value !== '') {
          queryParams.set(key, value.toString())
        }
      })
      
      const queryString = queryParams.toString()
      const targetUrl = queryString ? `/listings?${queryString}` : '/listings'
      
      navigate(targetUrl)
      
    } catch (error) {
      console.error('Navigation error:', error)
      const navigationError = error instanceof Error 
        ? error 
        : new Error('Unknown navigation error')
      
      onNavigationError?.(navigationError)
    } finally {
      setIsNavigating(false)
    }
  }

  return (
    <section 
      className={`bg-background ${className}`}
      aria-labelledby="popular-categories-heading"
    >
      <div className="mx-auto w-full max-w-[1440px] px-4 md:px-12">
        {/* Left-aligned header with proper accessibility */}
        <div className="mb-12">
          <h2 
            id="popular-categories-heading"
            className="text-3xl font-bold text-foreground"
          >
            {title}
          </h2>
        </div>

        {/* Responsive grid with proper ARIA labels */}
        <div 
          className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 lg:gap-6"
          role="group"
          aria-labelledby="popular-categories-heading"
        >
          {categories.map((category) => (
            <CategoryCard
              key={category.id}
              category={category}
              onClick={navigateToCategory}
              isLoading={isNavigating}
            />
          ))}
        </div>
      </div>
    </section>
  )
}

export default PopularCategories

// src/components/PopularCategories.vue
<template>
  <section :class="sectionClasses">
    <!-- Subtle top shadow/divider to separate from dark hero -->
    <div class="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-base-300 to-transparent"></div>
    
    <!-- Section Header -->
    <div class="mb-6 lg:mb-8">
      <h2 class="text-2xl lg:text-3xl font-bold text-base-content mb-3">
        Populære kategorier
      </h2>
    </div>

    <!-- Category Grid -->
    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 lg:gap-6">
      <div
        v-for="category in categories"
        :key="category.id"
        @click="navigateToCategory(category.filters)"
        class="group cursor-pointer w-full"
      >
        <div class="card card-compact bg-base-100 border border-base-300/50 hover:border-primary/20 hover:shadow-xl hover:-translate-y-1 hover:bg-base-50 transition-all duration-300 cursor-pointer group">
          <div class="card-body items-center text-center">
            <!-- Icon with enhanced animation -->
            <div class="text-primary group-hover:text-primary group-hover:scale-110 transition-all duration-300 mb-3">
              <component :is="category.icon" class="w-8 h-8 lg:w-10 lg:h-10" />
            </div>
            
            <!-- Enhanced content with DaisyUI 5 typography -->
            <div class="space-y-2">
              <h3 class="card-title text-sm sm:text-base group-hover:text-primary transition-colors duration-200 justify-center">
                {{ category.label }}
              </h3>
              
              <p class="text-xs text-base-content/60 leading-relaxed">
                {{ category.subtitle }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- CTA Section -->
    <div class="text-center mt-8 lg:mt-12">
      <router-link 
        to="/listings" 
        class="inline-flex items-center text-primary hover:text-primary font-medium transition-all duration-200 hover:gap-3 group hover:opacity-90"
      >
        Se alle biler
        <ChevronRight class="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform duration-200" />
      </router-link>
    </div>
  </section>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Zap, DollarSign, Users, Building, Settings, ChevronRight } from 'lucide-vue-next'

const props = defineProps({
  noTopPadding: {
    type: Boolean,
    default: false
  }
})

const router = useRouter()

// Computed property for section classes
const sectionClasses = computed(() => {
  const baseClasses = 'relative'
  const paddingClasses = props.noTopPadding 
    ? 'pb-6 sm:pb-8' 
    : 'py-6 sm:py-8'
  
  return `${baseClasses} ${paddingClasses}`
})

// Category definitions with filters and styling
const categories = ref([
  {
    id: 'electric',
    label: 'Elbiler',
    subtitle: 'Miljøvenlige valg',
    icon: Zap,
    filters: {
      fuel_type: 'Electric'
    }
  },
  {
    id: 'cheap',
    label: 'Billige biler',
    subtitle: 'Under 2.000 kr./md',
    icon: DollarSign,
    filters: {
      price_max: 2000
    }
  },
  {
    id: 'family',
    label: 'Familiebiler',
    subtitle: 'SUV & Stationcars',
    icon: Users,
    filters: {
      body_type: 'SUV' // Note: We'll handle multiple types in the navigation
    }
  },
  {
    id: 'city',
    label: 'Bybiler',
    subtitle: 'Kompakte & smarte',
    icon: Building,
    filters: {
      body_type: 'Microcar'
    }
  },
  {
    id: 'automatic',
    label: 'Automatgear',
    subtitle: 'Nem kørsel',
    icon: Settings,
    filters: {
      transmission: 'Automatic'
    }
  }
])

// Navigation function
function navigateToCategory(filters) {
  // Handle special case for family cars (multiple body types)
  if (filters.body_type === 'SUV') {
    // For family cars, we'll just use SUV as the most common family car type
    // In a real implementation, you might want to handle multiple values
    router.push({ 
      path: '/listings', 
      query: { body_type: 'SUV' }
    })
    return
  }
  
  // Convert filters to query parameters
  const query = {}
  Object.entries(filters).forEach(([key, value]) => {
    if (value !== null && value !== undefined && value !== '') {
      query[key] = value
    }
  })
  
  router.push({ path: '/listings', query })
}
</script>

<style scoped>
/* Enhanced hover animations */
.group:hover .group-hover\:scale-110 {
  transform: scale(1.1);
}

/* Smooth card transitions */
.card {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

/* CTA hover effect */
.group:hover .group-hover\:translate-x-1 {
  transform: translateX(0.25rem);
}

/* Ensure consistent card heights on mobile */
@media (max-width: 640px) {
  .grid > div {
    min-height: 120px;
  }
}

/* Focus states for accessibility */
.cursor-pointer:focus {
  outline: 0;
}

.cursor-pointer:focus-visible .card {
  ring: 2px;
  ring-color: hsl(var(--p) / 0.2);
  ring-offset: 2px;
}
</style>
