// src/components/Header.vue
<script setup>
import { ref } from 'vue'

const mobileMenuOpen = ref(false)
</script>

<template>
  <header class="bg-neutral shadow-sm">
    <div class="mx-auto w-full max-w-[1440px] px-6 flex items-center justify-between h-16"> <!-- Reduced from h-20 to h-16 -->
      <!-- Logo -->
      <router-link to="/" class="text-2xl font-bold text-primary">
        Leasingbørsen
      </router-link>

      <!-- Desktop menu -->
      <ul class="hidden lg:flex space-x-8 text-base">
        <li><router-link to="/" class="text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Home</router-link></li>
        <li><router-link to="/listings" class="text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Listings</router-link></li>
        <li><router-link to="/create" class="text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Opret</router-link></li>
        <li><router-link to="/about" class="text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Om</router-link></li>
      </ul>

      <!-- Mobile menu toggle -->
      <button class="lg:hidden btn btn-square btn-ghost" @click="mobileMenuOpen = !mobileMenuOpen">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none"
          viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>

    <!-- Mobile menu -->
    <div v-if="mobileMenuOpen" class="lg:hidden">
      <div class="mx-auto w-full max-w-[1440px] px-6">
        <ul class="bg-neutral w-full py-3 rounded-lg shadow-lg space-y-2 text-base">
          <li><router-link to="/" @click="mobileMenuOpen = false" class="block px-4 py-2 text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Home</router-link></li>
          <li><router-link to="/listings" @click="mobileMenuOpen = false" class="block px-4 py-2 text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Listings</router-link></li>
          <li><router-link to="/create" @click="mobileMenuOpen = false" class="block px-4 py-2 text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Opret</router-link></li>
          <li><router-link to="/about" @click="mobileMenuOpen = false" class="block px-4 py-2 text-primary font-semibold hover:underline hover:bg-transparent hover:text-primary transition">Om</router-link></li>
        </ul>
      </div>
    </div>
  </header>
</template>

// react-poc/leasingborsen-react-production/src/components/Header.tsx
import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { useThemeStore, THEMES } from '@/stores/themeStore'

const Header: React.FC = () => {
  const { currentTheme, setTheme } = useThemeStore()
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <header className="bg-card border-b border-border shadow-sm sticky top-0 z-50">
      <div className="mx-auto max-w-[1440px] px-6">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <div className="flex items-center">
            <Link to="/" className="text-2xl font-bold text-primary hover:text-primary/80 transition-colors">
              Leasingbørsen
            </Link>
          </div>

          {/* Navigation */}
          <nav className="flex space-x-4 md:space-x-8">
            <Link 
              to="/" 
              className="text-foreground hover:text-primary transition-colors font-medium"
            >
              Hjem
            </Link>
            <Link 
              to="/listings" 
              className="text-foreground hover:text-primary transition-colors font-medium"
            >
              Biler
            </Link>
            <Link 
              to="/about" 
              className="text-foreground hover:text-primary transition-colors font-medium"
            >
              Om os
            </Link>
          </nav>

          {/* Theme Selector */}
          <div className="flex items-center space-x-4">
            <select
              value={currentTheme}
              onChange={(e) => setTheme(e.target.value as typeof THEMES[number])}
              className="bg-background border border-border rounded-md px-3 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
            >
              {THEMES.map((theme) => (
                <option key={theme} value={theme}>
                  {theme.charAt(0).toUpperCase() + theme.slice(1)}
                </option>
              ))}
            </select>
          </div>

          {/* Mobile menu button */}
          <div className="md:hidden">
            <button 
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="text-foreground hover:text-primary transition-colors"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                {mobileMenuOpen ? (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                ) : (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                )}
              </svg>
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-card border-t border-border">
            <nav className="px-6 py-4 space-y-3">
              <Link 
                to="/" 
                className="block text-foreground hover:text-primary transition-colors font-medium"
                onClick={() => setMobileMenuOpen(false)}
              >
                Hjem
              </Link>
              <Link 
                to="/listings" 
                className="block text-foreground hover:text-primary transition-colors font-medium"
                onClick={() => setMobileMenuOpen(false)}
              >
                Biler
              </Link>
              <Link 
                to="/about" 
                className="block text-foreground hover:text-primary transition-colors font-medium"
                onClick={() => setMobileMenuOpen(false)}
              >
                Om os
              </Link>
              <div className="pt-2 border-t border-border">
                <select
                  value={currentTheme}
                  onChange={(e) => setTheme(e.target.value as typeof THEMES[number])}
                  className="w-full bg-background border border-border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
                >
                  {THEMES.map((theme) => (
                    <option key={theme} value={theme}>
                      {theme.charAt(0).toUpperCase() + theme.slice(1)}
                    </option>
                  ))}
                </select>
              </div>
            </nav>
          </div>
        )}
      </div>
    </header>
  )
}

export default Header
