// src/pages/Listings.vue
<!-- Enhanced Listings.vue with seamless header-to-filter transition -->
<template>
  <BaseLayout>
    <!-- 📱 Sticky Filter + Sort Bar - Full width outside container (MOBILE ONLY) -->
    <div
      class="lg:hidden sticky left-0 right-0 bg-card-bg shadow-sm border-b border-gray-200 z-40"
      :class="stickyFilterClasses"
      :style="stickyFilterStyle"
    >
      <div class="flex items-center gap-2 w-full max-w-[1440px] mx-auto px-6 py-3">
        <button
          @click="openMobileFilter"
          class="flex items-center gap-1 border border-gray-300 rounded-lg transition-all duration-300 h-10 px-3 hover:bg-gray-50 focus:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary/20 flex-shrink-0"
        >
          <Filter class="w-5 h-5" /> Filter
          <span v-if="activeFilters.length" class="bg-red-600 text-white rounded-full w-5 h-5 text-xs flex items-center justify-center">
            {{ activeFilters.length }}
          </span>
        </button>
        <!-- Filter chips in the same bar -->
        <div class="flex-1 overflow-x-auto">
          <FilterChips
            :activeFilters="activeFilters"
            @remove-filter="removeFilter"
            @reset-filters="resetAllFilters"
            class="flex gap-2 flex-nowrap"
          />
        </div>
      </div>
    </div>

    <div class="flex flex-col gap-2 lg:pt-6">
      <!-- 📱 MOBILE: Result count and sorting section -->
      <div class="lg:hidden">
        <div class="mt-6 mb-4 space-y-4">
          <!-- Result count - full width -->
          <div>
            <ListingResultsResultCount :count="resultCount" class="text-xl font-bold text-gray-900" />
          </div>
          
          <!-- Sorting row -->
          <div class="flex items-center">
            <div class="relative">
              <button
                @click="showMobileSortDropdown = !showMobileSortDropdown"
                class="flex items-center gap-2 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors duration-200 py-1"
              >
                <ArrowUpDown class="w-4 h-4 text-gray-500" />
                <span>{{ currentSortLabel }}</span>
                <ChevronDown class="w-3 h-3 text-gray-500 transition-transform duration-200" :class="{ 'rotate-180': showMobileSortDropdown }" />
              </button>
              
              <!-- Sort dropdown -->
              <div v-if="showMobileSortDropdown" class="absolute top-full left-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg py-2 z-50 min-w-[160px]">
                <button
                  @click="selectSortOption('')"
                  class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 transition-colors"
                  :class="{ 'text-primary font-medium': sortOrder === '' }"
                >
                  Lowest price
                </button>
                <button
                  @click="selectSortOption('desc')"
                  class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 transition-colors"
                  :class="{ 'text-primary font-medium': sortOrder === 'desc' }"
                >
                  Highest price
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- 🖥️ DESKTOP: Two Column Layout -->
      <div class="hidden lg:flex lg:gap-6">
        <!-- LEFT COLUMN: Filters -->
        <aside class="w-1/4">
          <FilterSidebar v-model:filters="filters" @update:sortOrder="sortOrder = $event" />
        </aside>
        
        <!-- RIGHT COLUMN: All Content -->
        <section class="flex-1">
          <!-- Top section with result count, chips, and sorting -->
          <div class="flex flex-col gap-4 mb-6">
            <!-- Result count and sorting row -->
            <div class="flex items-center justify-between">
              <ListingResultsResultCount :count="resultCount" class="text-2xl font-black" />
              <div class="relative">
                <button
                  @click="showDesktopSortDropdown = !showDesktopSortDropdown"
                  class="flex items-center gap-2 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors duration-200 py-1"
                >
                  <ArrowUpDown class="w-4 h-4 text-gray-500" />
                  <span>{{ currentSortLabel }}</span>
                  <ChevronDown class="w-3 h-3 text-gray-500 transition-transform duration-200" :class="{ 'rotate-180': showDesktopSortDropdown }" />
                </button>
                
                <!-- Desktop Sort dropdown -->
                <div v-if="showDesktopSortDropdown" class="absolute top-full right-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg py-2 z-50 min-w-[160px]">
                  <button
                    @click="selectDesktopSortOption('')"
                    class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 transition-colors"
                    :class="{ 'text-primary font-medium': sortOrder === '' }"
                  >
                    Lowest price
                  </button>
                  <button
                    @click="selectDesktopSortOption('desc')"
                    class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 transition-colors"
                    :class="{ 'text-primary font-medium': sortOrder === 'desc' }"
                  >
                    Highest price
                  </button>
                </div>
              </div>
            </div>
            
            <!-- Filter chips -->
            <div>
              <FilterChips
                :activeFilters="activeFilters"
                @remove-filter="removeFilter"
                @reset-filters="resetAllFilters"
                class="flex flex-wrap gap-2"
              />
            </div>
          </div>

          <!-- Listing Results -->
          <ListingResults
            :filters="filters"
            :sortOrder="sortOrder"
            @update:filters="filters = $event"
            @update:count="resultCount = $event"
          />
        </section>
      </div>

      <!-- 📱 MOBILE: Results Section -->
      <section class="lg:hidden">
        <ListingResults
          :filters="filters"
          :sortOrder="sortOrder"
          @update:filters="filters = $event"
          @update:count="resultCount = $event"
        />
      </section>

      <!-- Mobile Filter Overlay -->
      <MobileFilterOverlay 
        v-show="showMobileFilter" 
        v-model:filters="filters" 
        @close="closeMobileFilter"
        @apply-filters="handleApplyFilters"
      />
    </div>
  </BaseLayout>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import BaseLayout from '../components/BaseLayout.vue'
import FilterSidebar from '../components/FilterSidebar.vue'
import ListingResults from '../components/ListingResults.vue'
import ListingResultsResultCount from '../components/ListingResultsResultCount.vue'
import FilterChips from '../components/FilterChips.vue'
import MobileFilterOverlay from '../components/MobileFilterOverlay.vue'
import { Filter, ChevronDown, ArrowUpDown } from 'lucide-vue-next'

const defaultFilters = {
  make: '', model: '', fuel_type: '', transmission: '', body_type: '',
  horsepower: null, seats_min: null, seats_max: null,
  price_min: null, price_max: null, condition: '',
  listingStatus: '', driveType: '', availableBefore: ''
}

const filters = ref({ ...defaultFilters })
const resultCount = ref(0)
const sortOrder = ref('')
const showMobileFilter = ref(false)
const scrollY = ref(0)
const isApplyingFilters = ref(false)
const showMobileSortDropdown = ref(false)
const showDesktopSortDropdown = ref(false)

// Constants for better maintainability
const HEADER_HEIGHT = 64

onMounted(() => {
  const handleScroll = () => {
    scrollY.value = window.scrollY
  }
  
  // Use passive listener for better performance
  window.addEventListener('scroll', handleScroll, { passive: true })
  
  onUnmounted(() => {
    window.removeEventListener('scroll', handleScroll)
  })
})

// Sticky positioning based on header scroll
const stickyFilterStyle = computed(() => {
  const topPosition = Math.max(HEADER_HEIGHT - scrollY.value, 0)
  
  return {
    top: `${topPosition}px`,
    width: '100vw',
    marginLeft: 'calc(-50vw + 50%)'
  }
})

// Enhanced sticky classes
const stickyFilterClasses = computed(() => {
  const isSticky = scrollY.value >= HEADER_HEIGHT
  return {
    'shadow-lg': isSticky,
    'backdrop-blur-sm': isSticky,
    'bg-white/95': isSticky,
    'border-t': !isSticky, // Only show top border when not sticky
  }
})

// Active filters computation
const activeFilters = computed(() => {
  const f = filters.value
  const list = []
  const transmissionLabels = {
    'Automatic': 'Automatisk gear',
    'Manual': 'Manuelt gear'
  }
  
  if (f.make) list.push({ key: 'make', label: f.make })
  if (f.model) list.push({ key: 'model', label: f.model })
  if (f.fuel_type) list.push({ key: 'fuel_type', label: f.fuel_type })
  if (f.body_type) list.push({ key: 'body_type', label: f.body_type })
  if (f.transmission) list.push({ 
    key: 'transmission', 
    label: transmissionLabels[f.transmission] || f.transmission 
  })
  if (f.seats_min != null || f.seats_max != null) {
    const min = f.seats_min ?? ''
    const max = f.seats_max ?? ''
    list.push({ key: 'seats', label: `Sæder: ${min} - ${max}` })
  }
  if (f.price_min != null || f.price_max != null) {
    const min = f.price_min ?? ''
    const max = f.price_max ?? ''
    list.push({ key: 'price', label: `Pris: ${min} - ${max} kr.` })
  }
  
  return list
})

// Computed property for current sort label
const currentSortLabel = computed(() => {
  switch (sortOrder.value) {
    case 'desc': return 'Highest price'
    default: return 'Lowest price'
  }
})

function openMobileFilter() {
  showMobileFilter.value = true
}

function closeMobileFilter() {
  showMobileFilter.value = false
}

function handleApplyFilters(newFilters) {
  const exactScrollPosition = scrollY.value
  
  // Close overlay first
  closeMobileFilter()
  
  // Use nextTick to wait for overlay to close, then update filters
  nextTick(() => {
    // Update filters after overlay is closed
    filters.value = { ...newFilters }
    
    // Immediately restore scroll position
    window.scrollTo({
      top: exactScrollPosition,
      behavior: 'instant'
    })
  })
}

function removeFilter(key) {
  const updated = { ...filters.value }
  
  if (key === 'seats') {
    updated.seats_min = null
    updated.seats_max = null
  } else if (key === 'price') {
    updated.price_min = null
    updated.price_max = null
  } else {
    updated[key] = ''
  }
  
  filters.value = updated
}

function resetAllFilters() {
  filters.value = { ...defaultFilters }
}

function selectSortOption(option) {
  sortOrder.value = option
  showMobileSortDropdown.value = false
}

function selectDesktopSortOption(option) {
  sortOrder.value = option
  showDesktopSortDropdown.value = false
}
</script>

// react-poc/leasingborsen-react-production/src/pages/Listings.tsx
import React, { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { 
  Filter, 
  SlidersHorizontal, 
  ArrowUpDown, 
  ChevronDown 
} from 'lucide-react'
import { useListings } from '@/hooks/useListings'
import { useFilterStore } from '@/stores/filterStore'
import BaseLayout from '@/components/BaseLayout'
import Container from '@/components/Container'
import FilterSidebar from '@/components/FilterSidebar'
import FilterChips from '@/components/FilterChips'
import MobileFilterOverlay from '@/components/MobileFilterOverlay'
import ListingCard from '@/components/ListingCard'
import type { SortOrder, SortOption } from '@/types'

// Sort options configuration
const sortOptions: SortOption[] = [
  { value: '', label: 'Laveste pris' },
  { value: 'desc', label: 'Højeste pris' }
]

const Listings: React.FC = () => {
  const [searchParams] = useSearchParams()
  const [mobileFilterOpen, setMobileFilterOpen] = useState(false)
  const [showSortDropdown, setShowSortDropdown] = useState(false)
  
  const { 
    makes = [],
    models = [],
    body_type,
    fuel_type,
    transmission,
    price_min,
    price_max,
    seats_min,
    seats_max,
    horsepower_min,
    horsepower_max,
    sortOrder,
    setFilter,
    setSortOrder,
    getActiveFilters,
    resetFilters
  } = useFilterStore()

  // Initialize filters from URL params
  useEffect(() => {
    const urlMake = searchParams.get('make')
    const urlModel = searchParams.get('model')
    const urlBodyType = searchParams.get('body_type')
    const urlFuelType = searchParams.get('fuel_type')
    const urlTransmission = searchParams.get('transmission')
    const urlPriceMin = searchParams.get('price_min')
    const urlPriceMax = searchParams.get('price_max')
    const urlSeatsMin = searchParams.get('seats_min')
    const urlSeatsMax = searchParams.get('seats_max')
    const urlHorsepowerMin = searchParams.get('horsepower_min')
    const urlHorsepowerMax = searchParams.get('horsepower_max')
    const urlSort = searchParams.get('sort')

    if (urlMake && !makes.includes(urlMake)) setFilter('makes', [urlMake])
    if (urlModel && !models.includes(urlModel)) setFilter('models', [urlModel])
    
    // Handle array-based filters
    if (urlBodyType) {
      const bodyTypeArray = urlBodyType.split(',').filter(Boolean)
      if (JSON.stringify(bodyTypeArray) !== JSON.stringify(body_type)) {
        setFilter('body_type', bodyTypeArray)
      }
    }
    if (urlFuelType) {
      const fuelTypeArray = urlFuelType.split(',').filter(Boolean)
      if (JSON.stringify(fuelTypeArray) !== JSON.stringify(fuel_type)) {
        setFilter('fuel_type', fuelTypeArray)
      }
    }
    if (urlTransmission) {
      const transmissionArray = urlTransmission.split(',').filter(Boolean)
      if (JSON.stringify(transmissionArray) !== JSON.stringify(transmission)) {
        setFilter('transmission', transmissionArray)
      }
    }
    
    if (urlPriceMin && parseInt(urlPriceMin) !== price_min) setFilter('price_min', parseInt(urlPriceMin))
    if (urlPriceMax && parseInt(urlPriceMax) !== price_max) setFilter('price_max', parseInt(urlPriceMax))
    if (urlSeatsMin && parseInt(urlSeatsMin) !== seats_min) setFilter('seats_min', parseInt(urlSeatsMin))
    if (urlSeatsMax && parseInt(urlSeatsMax) !== seats_max) setFilter('seats_max', parseInt(urlSeatsMax))
    if (urlHorsepowerMin && parseInt(urlHorsepowerMin) !== horsepower_min) setFilter('horsepower_min', parseInt(urlHorsepowerMin))
    if (urlHorsepowerMax && parseInt(urlHorsepowerMax) !== horsepower_max) setFilter('horsepower_max', parseInt(urlHorsepowerMax))
    if (urlSort && urlSort !== sortOrder) setSortOrder(urlSort as SortOrder)
  }, [searchParams])

  const currentFilters = { 
    makes,
    models,
    body_type, 
    fuel_type, 
    transmission, 
    price_min, 
    price_max, 
    seats_min, 
    seats_max, 
    horsepower_min,
    horsepower_max
  }
  const { data: listingsResponse, isLoading, error } = useListings(currentFilters, 20, sortOrder)

  const listings = listingsResponse?.data || []
  const resultCount = listings.length
  const activeFilters = getActiveFilters()

  // Get current sort label
  const currentSortLabel = sortOptions.find(option => option.value === sortOrder)?.label || 'Laveste pris'

  // Handle sort selection
  const handleSortChange = (newSortOrder: SortOrder) => {
    setSortOrder(newSortOrder)
    setShowSortDropdown(false)
  }

  // Handle filter removal
  const handleRemoveFilter = (key: string) => {
    if (key === 'seats') {
      setFilter('seats_min', null)
      setFilter('seats_max', null)
    } else if (key === 'price') {
      setFilter('price_min', null)
      setFilter('price_max', null)
    } else if (key === 'makes') {
      setFilter('makes', [])
    } else if (key === 'models') {
      setFilter('models', [])
    } else if (key === 'body_type') {
      setFilter('body_type', [])
    } else if (key === 'fuel_type') {
      setFilter('fuel_type', [])
    } else if (key === 'transmission') {
      setFilter('transmission', [])
    } else if (key === 'horsepower') {
      setFilter('horsepower_min', null)
      setFilter('horsepower_max', null)
    }
  }

  return (
    /* =================================================
       LISTINGS PAGE LAYOUT - Following homepage container pattern
       Uses BaseLayout with consistent Container component
    ================================================= */
    <BaseLayout>
      {/* Mobile: Sticky Filter Bar - positioned outside Container for proper sticky behavior */}
      <div className="lg:hidden sticky top-0 bg-card/95 backdrop-blur-sm border-b border-border/50 z-50">
        <div className="px-4 py-3">
          <div className="flex items-center gap-3 h-8 overflow-x-auto scrollbar-hide">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setMobileFilterOpen(!mobileFilterOpen)}
              className="flex items-center gap-2 flex-shrink-0 h-8"
            >
              <SlidersHorizontal className="w-4 h-4" />
              Filtre
              {activeFilters.length > 0 && (
                <span className="bg-primary text-primary-foreground rounded-full w-5 h-5 text-xs flex items-center justify-center">
                  {activeFilters.length}
                </span>
              )}
            </Button>
            
            {/* Mobile Filter Chips - same row as filter button */}
            {activeFilters.length > 0 && (
              <FilterChips
                activeFilters={activeFilters}
                onRemoveFilter={handleRemoveFilter}
                onResetFilters={resetFilters}
                className="flex-shrink-0"
                showPlaceholder={false}
              />
            )}
          </div>
        </div>
      </div>

      {/* =================
          MAIN CONTENT WRAPPER - Using consistent Container component
      ================= */}
      <Container className="py-6 lg:py-12">
          {/* =================
              MAIN CONTENT LAYOUT - Improved spacing and layout
          ================= */}
          <div className="flex gap-8 lg:gap-10">
            
            {/* Desktop Sidebar - Enhanced width and styling */}
            <aside className="hidden lg:block w-80 xl:w-96 flex-shrink-0">
              <FilterSidebar />
            </aside>

            {/* Mobile Filter Overlay */}
            <MobileFilterOverlay
              isOpen={mobileFilterOpen}
              onClose={() => setMobileFilterOpen(false)}
              resultCount={resultCount}
            />

            {/* Main Content Area - Enhanced spacing */}
            <div className="flex-1 min-w-0">

              {/* Mobile: Result count */}
              <div className="lg:hidden flex items-center mb-6">
                <span className="text-lg font-bold text-foreground">
                  {resultCount} {resultCount === 1 ? 'bil' : 'biler'}
                </span>
              </div>

              {/* Desktop: Result count + sorting + filter chips */}
              <div className="hidden lg:block mb-8">
                {/* Result count and sorting row */}
                <div className="flex justify-between items-center mb-6">
                  <span className="text-xl font-bold text-foreground">
                    {resultCount} {resultCount === 1 ? 'bil fundet' : 'biler fundet'}
                  </span>
                  
                  {/* Sort Dropdown */}
                  <div className="relative">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setShowSortDropdown(!showSortDropdown)}
                      className="flex items-center gap-2"
                    >
                      <ArrowUpDown className="w-4 h-4" />
                      <span>{currentSortLabel}</span>
                      <ChevronDown className={`w-3 h-3 transition-transform duration-200 ${showSortDropdown ? 'rotate-180' : ''}`} />
                    </Button>
                    
                    {showSortDropdown && (
                      <div className="absolute top-full right-0 mt-2 bg-card border border-border rounded-lg shadow-lg py-2 z-50 min-w-[180px]">
                        {sortOptions.map((option) => (
                          <button
                            key={option.value}
                            onClick={() => handleSortChange(option.value)}
                            className={`w-full text-left px-4 py-2 text-sm hover:bg-muted transition-colors duration-200 ${
                              sortOrder === option.value ? 'text-primary font-medium bg-muted' : ''
                            }`}
                          >
                            {option.label}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                {/* Filter chips */}
                <FilterChips
                  activeFilters={activeFilters}
                  onRemoveFilter={handleRemoveFilter}
                  onResetFilters={resetFilters}
                  className="flex flex-wrap gap-2"
                />
              </div>

              
              {/* Error State - Enhanced styling */}
              {error && (
                <div className="bg-destructive/10 text-destructive border border-destructive/20 p-6 rounded-lg mb-8">
                  <h3 className="font-semibold mb-2">Der opstod en fejl</h3>
                  <p>Der opstod en fejl ved indlæsning af biler. Prøv igen senere.</p>
                </div>
              )}

              {/* Loading State - Grid layout */}
              {isLoading && (
                <div className="grid gap-6 lg:gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3">
                  {Array.from({ length: 9 }).map((_, i) => (
                    <ListingCard key={i} loading={true} />
                  ))}
                </div>
              )}

              {/* Results Display - Grid layout */}
              {!isLoading && !error && (
                <>
                  {listings.length > 0 ? (
                    <div className="grid gap-6 lg:gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3">
                      {listings.map((car) => (
                        <ListingCard 
                          key={car.listing_id || car.id} 
                          car={{
                            ...car,
                            id: car.listing_id || car.id
                          }} 
                        />
                      ))}
                    </div>
                  ) : (
                    /* Enhanced Empty State */
                    <div className="text-center py-16 lg:py-20">
                      <div className="max-w-md mx-auto space-y-6">
                        <div className="w-20 h-20 mx-auto bg-muted rounded-full flex items-center justify-center">
                          <Filter className="w-10 h-10 text-muted-foreground" />
                        </div>
                        <div className="space-y-2">
                          <h3 className="text-2xl font-bold text-foreground">
                            Ingen biler fundet
                          </h3>
                          <p className="text-muted-foreground leading-relaxed">
                            Der er ingen biler, der matcher dine søgekriterier. 
                            Prøv at justere filtrene for at se flere resultater.
                          </p>
                        </div>
                        <Button
                          variant="outline"
                          size="lg"
                          onClick={() => {
                            window.location.href = '/listings'
                          }}
                          className="mt-6"
                        >
                          Nulstil alle filtre
                        </Button>
                      </div>
                    </div>
                  )}
                </>
              )}

              {/* Load More Section - Enhanced styling */}
              {!isLoading && listings.length > 0 && listings.length >= 20 && (
                <div className="text-center mt-16 lg:mt-20">
                  <Button 
                    variant="outline" 
                    size="lg"
                    className="px-8 py-3 font-semibold"
                  >
                    Indlæs flere biler
                  </Button>
                </div>
              )}
            </div>
          </div>
      </Container>
    </BaseLayout>
  )
}

export default Listings
